# This script is used to precompile vignettes and should be run for
# each new version of the package

# Get current wd (to restore later)
old_wd <- getwd()
# Set wd to vignettes to avoid saving to base directory
setwd("vignettes/")
# Precompile vignettes
library(knitr)
knit("./source/_phanerozoic-reefs.Rmd",
     "phanerozoic-reefs.Rmd")
knit("./source/_tetrapod-biodiversity.Rmd",
     "tetrapod-biodiversity.Rmd")

# Build vignettes
library(devtools)
build_vignettes()

# x = vignette file name including file extension (e.g. "phanerozoic-reefs.Rmd")
read_only <- function(x) {
  # Create file
  tmp <- file(x)
  # write lines
  writeLines(c(c("---"),
               c("# Generated by vignettes/precompile.R: do not edit by hand."),
               paste0("# Please edit source in vignettes/source/_", x),
               readLines(x)[2:length(readLines(x))]), tmp)
  close(tmp)
}
# Add read only info
read_only("phanerozoic-reefs.Rmd")
read_only("tetrapod-biodiversity.Rmd")
rm(read_only)

# Restore wd
setwd(old_wd)
