#' Geological Time Scale 2020
#'
#' A dataset of the Geological Time Scale 2020. Age data from:
#'  \url{https://stratigraphy.org/timescale/}.
#' Definitions of relative climate states are also included in the dataset, and were compiled from various resources (see item descriptions).
#' Supplementary information is also included in the dataset for plotting functionality (e.g. GTS2020 colour scheme).
#'
#' @format A data frame with 189 rows and 20 variables:
#' \describe{
#'   \item{index}{Add description}
#'   \item{stage_number}{Add description}
#'   \item{series_number}{Add description}
#'   \item{system_number}{Add description}
#'   \item{interval_name}{Add description}
#'   \item{rank}{Add description}
#'   \item{max_ma}{Add description}
#'   \item{mid_ma}{Add description}
#'   \item{min_ma}{Add description}
#'   \item{duration_myr}{Add description}
#'   \item{climate_state_frakes_1992}{Add description}
#'   \item{climate_state_hay_2016}{Add description}
#'   \item{climate_Gradient_boucot_2013}{Add description}
#'   \item{co2_foster_2017}{Add description}
#'   \item{glaciogenic_detritus_cather_2009}{Add description}
#'   \item{glacial_deposits_cao_2019}{Add description}
#'   \item{climate_bin}{Add description}
#'   \item{climate_state}{Add description}
#'   \item{font}{Add description}
#'   \item{colour}{Add description}
#'   ...
#' }
#' @source Compiled by Lewis A. Jones from various sources. See item descriptions for details.
"GTS2020"
#' Palaeogeographic reconstruction grid
#'
#' Palaeogeographic coordinates of a 1º x 1º spatial grid rotated to the midpoints of stratigraphic stages
#' throughout the Phanerozoic (0--540 Ma). Midpoint ages are based on the Geological Timescale 2020 and \url{https://stratigraphy.org/timescale/}.
#'
#' @format A matrix with 64800 rows and 198 columns:
#' \describe{
#'   \item{lng}{Add description}
#'   \item{lat}{Add description}
#'   \item{lng_}{Add description}
#'   \item{lat_}{Add description}
#'   ...
#' }
#' @source Generated by Lewis A. Jones using a 1º x 1º spatial grid with the
#' GPlates software \url{https://www.gplates.org} and the plate rotation model
#' PALEOMAP (Scotese and Wright, 2018).
#' Scotese, C., & Wright, N. M. (2018). PALEOMAP Paleodigital Elevation Models (PaleoDEMS) for the Phanerozoic. PALEOMAP Project.
#' \url{https://www.earthbyte.org/paleodem-resource-scotese-and-wright-2018/}
"palaeo_rots"
