on:
  workflow_dispatch: # to be able to trigger this workflow by hand
  push:
    branches:
      - main
  schedule:
    - cron:  '0 12 * * 0' # weekly on Sunday at 12:00

name: Update allcontributors

permissions:
  contents: write
  pull-requests: write

jobs:

  allcontributors:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Update allcontributors

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2

      - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          cache-version: 5
          extra-packages: any::allcontributors

      - name: Update allcontributors
        run: Rscript -e 'allcontributors::add_contributors(ncols = 5, num_sections = 1)'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: 'Update allcontributors in README.md'
          author: 'Github Actions <github-actions@github.com>'
          committer: 'Github Actions <github-actions@github.com>'
          branch: update-allcontributors
          delete-branch: true
          title: 'Update allcontributors in README.md'
          body: 'Automated update of the contributors list in README.md.'
          add-paths: README.md
          token: ${{ secrets.ALLCONTRIBUTORS_PAT }}
