name: Check spelling

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          use-public-rspm: true

      - name: Spell check
        run: |
          install.packages(c("spelling", "cli"))
          options(crayon.enabled = TRUE)
          spelling_mistakes <- spelling::spell_check_package()
          cli::cli_rule()
          if (length(spelling_mistakes$word) > 0L) {
            print(spelling_mistakes)
            cli::cli_abort("Spelling errors found. Either correct them or update `inst/WORDLIST` using `spelling::update_wordlist()`.")
          } else {
            cli::cli_alert_success("No spelling errors found.")
          }
          cli::cli_rule()
        shell: Rscript {0}
