# This workflow runs Air for formatting and Jarl for linting. It stores artifacts about the
# outcome of each tool and the PR number. Those artifacts are then used in the workflow 
# "format-lint-pr-comment.yaml" to post a comment so that it's clearer for external
# contributors.
#
# This could have been done in a single workflow with a "pull_request_target" trigger but
# this might have some security issues (this is unlikely in practice but still better to
# be ahead of it):
# https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

name: Format and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  format-air:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Air
        uses: posit-dev/setup-air@f3a5b6aec110503f81b8d69439023308ebdf4874 # v1
      - name: Check
        id: check
        run: air format . --check
        continue-on-error: true
      - name: Save results
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ steps.check.outcome }}" > /tmp/air-result.txt
          echo "${{ github.event.pull_request.number }}" > /tmp/pr-number.txt
      - name: Upload artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: air-results
          path: |
            /tmp/air-result.txt
            /tmp/pr-number.txt
      - if: steps.check.outcome == 'failure'
        run: exit 1

  lint-jarl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check
        id: check
        uses: etiennebacher/setup-jarl@eabf7e572f2991d165059007531b9bbe2987e39c # v0.1.1
        continue-on-error: true
      - name: Save result
        if: github.event_name == 'pull_request'
        run: echo "${{ steps.check.outcome }}" > /tmp/jarl-result.txt
      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: jarl-results
          path: /tmp/jarl-result.txt
      - if: steps.check.outcome == 'failure'
        run: exit 1
