# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: r-lib/actions/setup-pandoc@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2

      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@d3c5be51b12e724e68f33216ca3c148b66d5f0b6 # v2
        with:
          extra-packages: any::pkgdown, any::brand.yml, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      # This is almost the same call as in check-links.yaml but this time we run it on the 
      # rendered pkgdown website. The reason for that is that lychee apparently doesn't find 
      # links in Rd files or in vignettes because of the file format, but it will be able to
      # check them in the rendered HTML files.
      #
      # New pages created by the PR do not exist yet on the rendered website so we need to
      # "remap" those links to the github workspace used by this branch. We need to remap two 
      # kinds of links:
      # - links to palaeoverse.palaeoverse.org, e.g. a reference page for a new function
      # - links to github.com/palaeoverse/palaeoverse/blob/HEAD, e.g. links to the source 
      #   code that exist at the top of each reference page. If we add a new reference page
      #   in a PR then the source code may not exist yet on the main branch. 
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@649b0e4890508ea3e11ea6b3ee35ce899a25afd5 # v2
        with:
          args: |
            docs
            --root-dir=${{ github.workspace }}/docs
            --remap 'https://palaeoverse\.palaeoverse\.org/(.*) file://${{ github.workspace }}/docs/$1'
            --remap 'https://github\.com/palaeoverse/palaeoverse/blob/HEAD/(.*) file://${{ github.workspace }}/$1'
            --max-concurrency 4
            --max-retries 5
            --retry-wait-time 5
            --timeout 10
            --exclude '(^https://doi\.org)|(fsf\.org)|(gnu\.org)|(researchgate\.net)'
            --accept 200,429

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
