# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - .github/workflows/R-CMD-check.yaml
      - .Rbuildignore
      - data/**
      - man/**
      - R/**
      - inst/**
      - tests/**
      - vignettes/*
      - DESCRIPTION
      - NAMESPACE
  pull_request:
    branches: [main, master]
    paths:
      - .github/workflows/R-CMD-check.yaml
      - .Rbuildignore
      - data/**
      - man/**
      - R/**
      - inst/**
      - tests/**
      - vignettes/*
      - DESCRIPTION
      - NAMESPACE
  schedule:
    # Every Monday at 8am
    - cron: "0 8 * * 1"

name: R-CMD-check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}
          - {os: ubuntu-latest,  r: 'oldrel-2'}
          - {os: ubuntu-latest,  r: 'oldrel-3'}
          - {os: ubuntu-latest,  r: 'oldrel-4'}
          - {os: ubuntu-latest,  r: 'oldrel-5'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: r-lib/actions/setup-pandoc@9f58233a78a2a9fd874714be10f8bba627233339 # v2

      - uses: r-lib/actions/setup-r@9f58233a78a2a9fd874714be10f8bba627233339 # v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # Some packages (e.g. geosphere) have compilation errors on R 4.1 and 4.2 because by default they
      # use C++14 while they require C++17. We manually set this required C++ version for those R 
      # versions only.
      - name: Set C++17 compiler for older R versions
        if: ${{ matrix.config.r == 'oldrel-4' || matrix.config.r == 'oldrel-5' }}
        run: |
          mkdir -p ~/.R
          echo "CXX = g++ -std=gnu++17" >> ~/.R/Makevars
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2
        env:
          _R_CHECK_FORCE_SUGGESTS_: 0
        with:
          upload-snapshots: true
          args: 'c("--no-manual", "--as-cran", "--no-vignettes", "--ignore-vignettes")'
          build_args: 'c("--no-manual", "--no-build-vignettes")'
